### ISSUE TITLE
[solved] how to make the triggerbot shoot

### ISSUE THREAD

**Issue by ghost** [superboxes/valorant-colorbot#1]
how do i make it start aiming or shooting lol

**Comment by superboxes** [comment]
by holding the trigger_key you set in config.json

**Comment by ghost** [comment]
> by holding the trigger_key you set in config.json

yeah nothing happens when i hold it

**Comment by ghost** [comment]
yo?

**Comment by superboxes** [comment]
dont forget to change the color of enemy outline to match your config.json. Same with the shoot_button from config.json and secondary fire button in val settings. Look through the source code if you dont understand anything else.
